# Generated by Django 4.0.1 on 2024-07-04 20:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('denomination', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('metal', models.CharField(max_length=100)),
                ('year', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Condition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CoinStateCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField(default=0)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('coin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mycoinApp.coin')),
                ('condition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mycoinApp.condition')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mycoinApp.state')),
            ],
            options={
                'unique_together': {('coin', 'state', 'condition')},
            },
        ),
    ]
