# Generated by Django 4.0.1 on 2024-07-04 20:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
        ('mycoinApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coinstatecondition',
            name='count',
        ),
        migrations.CreateModel(
            name='UserCoinOwnership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField(default=0)),
                ('coin_state_condition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mycoinApp.coinstatecondition')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coin_ownerships', to='authentication.user')),
            ],
            options={
                'unique_together': {('user', 'coin_state_condition')},
            },
        ),
    ]
