# Generated by Django 4.0.1 on 2024-07-06 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycoinApp', '0002_remove_coinstatecondition_count_usercoinownership'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coinstatecondition',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
