# Generated by Django 4.0.1 on 2024-07-06 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycoinApp', '0003_alter_coinstatecondition_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='coinstatecondition',
            name='back_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/coins'),
        ),
        migrations.AddField(
            model_name='coinstatecondition',
            name='front_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/coins'),
        ),
    ]
