# Generated by Django 4.0.1 on 2024-07-12 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycoinApp', '0005_alter_coinstatecondition_back_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercoinownership',
            name='request',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
