# Generated by Django 4.0.1 on 2024-07-17 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mycoinApp', '0007_pushnotification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PushNotification',
        ),
    ]
