# Generated by Django 5.1.1 on 2024-11-25 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycoinApp', '0011_passwordresettoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='coinstatecondition',
            name='inclusion_status',
            field=models.CharField(choices=[('Y', 'Compulsory'), ('R', 'Recommended'), ('N', 'Not Included')], default='N', max_length=1),
        ),
    ]
