# Generated by Django 5.1.1 on 2024-12-05 18:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycoinApp', '0013_alter_universecoinset_coin_set'),
    ]

    operations = [
        migrations.AddField(
            model_name='universecoinset',
            name='set_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mycoinApp.setnamecoins'),
        ),
    ]
