# Generated by Django 5.1.1 on 2024-11-25 18:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_remove_user_last_login'),
        ('mycoinApp', '0013_usersetofcoins'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='usersetofcoins',
            unique_together={('user', 'coin_set')},
        ),
        migrations.AddField(
            model_name='usersetofcoins',
            name='coin_state_condition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mycoinApp.coinstatecondition'),
        ),
        migrations.RemoveField(
            model_name='usersetofcoins',
            name='coin',
        ),
    ]
