# Generated by Django 5.1.1 on 2024-12-09 05:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycoinApp', '0014_universecoinset_set_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='universecoinset',
            name='coin_set',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mycoinApp.usersetofcoin'),
        ),
    ]
