# Generated by Django 5.1.1 on 2024-11-26 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mycoinApp', '0014_alter_usersetofcoins_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='usersetofcoins',
            unique_together=set(),
        ),
    ]
