# Generated by Django 5.1.1 on 2024-11-27 12:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycoinApp', '0015_alter_usersetofcoins_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersetofcoins',
            name='coin_state_condition',
        ),
        migrations.AddField(
            model_name='usersetofcoins',
            name='coin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mycoinApp.coin'),
        ),
    ]
