# Generated by Django 5.1.1 on 2024-12-09 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycoinApp', '0015_alter_universecoinset_coin_set'),
    ]

    operations = [
        migrations.AlterField(
            model_name='universecoinset',
            name='coin_set',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
