# Generated by Django 5.1.1 on 2024-11-28 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycoinApp', '0016_remove_usersetofcoins_coin_state_condition_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersetofcoins',
            name='coin',
        ),
        migrations.AddField(
            model_name='usersetofcoins',
            name='coin_state_condition',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
