# Generated by Django 5.1.1 on 2024-12-09 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycoinApp', '0017_alter_universecoinset_coin_set'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='universecoinset',
            name='coin_set',
        ),
        migrations.AddField(
            model_name='universecoinset',
            name='coin_set',
            field=models.ManyToManyField(blank=True, null=True, to='mycoinApp.usersetofcoin'),
        ),
    ]
