# Generated by Django 5.1.1 on 2024-11-29 18:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycoinApp', '0017_remove_usersetofcoins_coin_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersetofcoins',
            name='coin_set',
        ),
        migrations.AddField(
            model_name='usersetofcoins',
            name='coin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mycoinApp.coin'),
        ),
    ]
