# Generated by Django 5.1.1 on 2024-12-09 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycoinApp', '0018_remove_universecoinset_coin_set_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='universecoinset',
            name='coin_set',
            field=models.ManyToManyField(to='mycoinApp.usersetofcoin'),
        ),
    ]
