# Generated by Django 5.1.1 on 2024-11-30 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_remove_user_last_login'),
        ('mycoinApp', '0019_rename_coin_state_condition_usersetofcoins_set_counts'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='usersetofcoins',
            unique_together={('user', 'coin')},
        ),
    ]
