# Generated by Django 5.1.1 on 2024-12-14 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycoinApp', '0020_remove_universecoinset_coin_set_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='universecoinset',
            name='price',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
