# Generated by Django 5.1.1 on 2024-12-14 16:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycoinApp', '0021_universecoinset_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='setnamecoins',
            name='price',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='universecoinset',
            name='price',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='price_coins', to='mycoinApp.setnamecoins'),
        ),
        migrations.AlterField(
            model_name='universecoinset',
            name='set_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='set_name_coins', to='mycoinApp.setnamecoins'),
        ),
    ]
