# Generated by Django 5.1.1 on 2024-12-01 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_remove_user_last_login'),
        ('mycoinApp', '0021_usersetofcoins_set_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserSetOfCoins',
            new_name='UserSetOfCoin',
        ),
    ]
