# Generated by Django 5.1.1 on 2024-12-01 19:53

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_remove_user_last_login'),
        ('mycoinApp', '0022_rename_usersetofcoins_usersetofcoin'),
    ]

    operations = [
        migrations.CreateModel(
            name='SetNameCoins',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('set_name', models.CharField(blank=True, max_length=64, null=True)),
                ('coin_list', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), size=20)),
            ],
        ),
        migrations.CreateModel(
            name='UniverseCoinSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coin_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mycoinApp.usersetofcoin')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.user')),
            ],
        ),
    ]
