# Generated by Django 5.1.1 on 2024-12-02 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mycoinApp', '0024_alter_setnamecoins_coin_list'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SetNameCoins',
        ),
    ]
